DROP TABLE IF EXISTS `file_changes`;
CREATE TABLE `file_changes` (
  `id` varchar(36) NOT NULL,
  `repository_id` varchar(36) NOT NULL,
  `user_id` int DEFAULT NULL,
  `file_path` varchar(500) NOT NULL,
  `relative_path` varchar(500) NOT NULL,
  `change_type` varchar(20) NOT NULL,
  `git_diff` text,
  `author` varchar(255) DEFAULT NULL,
  `author_email` varchar(255) DEFAULT NULL,
  `commit_hash` varchar(40) DEFAULT NULL,
  `file_extension` varchar(10) DEFAULT NULL,
  `lines_added` int NOT NULL,
  `lines_removed` int NOT NULL,
  `timestamp` datetime NOT NULL,
  `is_processed` tinyint(1) NOT NULL,
  `sent_to_ai` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_file_changes_user_id` (`user_id`),
  KEY `ix_file_changes_relative_path` (`relative_path`),
  KEY `ix_file_changes_author_email` (`author_email`),
  KEY `ix_file_changes_timestamp` (`timestamp`),
  KEY `ix_file_changes_is_processed` (`is_processed`),
  KEY `ix_file_changes_file_extension` (`file_extension`),
  KEY `ix_file_changes_sent_to_ai` (`sent_to_ai`),
  KEY `ix_file_changes_change_type` (`change_type`),
  KEY `ix_file_changes_repository_id` (`repository_id`),
  KEY `ix_file_changes_file_path` (`file_path`),
  KEY `ix_file_changes_author` (`author`),
  KEY `ix_file_changes_commit_hash` (`commit_hash`),
  CONSTRAINT `file_changes_ibfk_1` FOREIGN KEY (`repository_id`) REFERENCES `repositories` (`id`) ON DELETE CASCADE,
  CONSTRAINT `file_changes_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
